
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ID\n    S : 'i' E 't' S S_prime\n      | 'a'\n    \n    S_prime : 'e' S\n            | empty\n    \n    E : 'b'\n    \n    empty :\n    "
    
_lr_action_items = {'i':([0,6,9,],[2,2,2,]),'a':([0,6,9,],[3,3,3,]),'$end':([1,3,7,8,10,11,],[0,-2,-6,-1,-4,-3,]),'b':([2,],[5,]),'e':([3,7,8,10,11,],[-2,9,-1,-4,-3,]),'t':([4,5,],[6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,6,9,],[1,7,11,]),'E':([2,],[4,]),'S_prime':([7,],[8,]),'empty':([7,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> i E t S S_prime','S',5,'p_S','prac7_yacc.py',11),
  ('S -> a','S',1,'p_S','prac7_yacc.py',12),
  ('S_prime -> e S','S_prime',2,'p_S_prime','prac7_yacc.py',17),
  ('S_prime -> empty','S_prime',1,'p_S_prime','prac7_yacc.py',18),
  ('E -> b','E',1,'p_E','prac7_yacc.py',23),
  ('empty -> <empty>','empty',0,'p_empty','prac7_yacc.py',28),
]
